---
version: "3.5"
services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "${DB_PORT:-27017}:27017"
    volumes:
      - type: bind
        source: ../dbdata-prod
        target: /data/db
    networks:
      - frontend

  back-end:
    container_name: courses-back-end
    restart: "on-failure"
    build:
      context: ./../back-end
      dockerfile: ./../config/Dockerfile-backend
    env_file:
      - ./../back-end/.env
    environment:
      NODE_ENV: production
      MONGODB_URI: "mongodb://mongo:${DB_PORT:-27017}/docker-node-mongo-prod"
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    depends_on:
      - "mongo"
    networks:
      - frontend

  front-end:
    container_name: courses-front-end
    restart: "on-failure"
    build:
      context: ./../front-end
      dockerfile: ./../config/Dockerfile-frontend
    ports:
      - "${FRONTEND_PORT:-80}:3000"
    depends_on:
      - "back-end"
    env_file:
      - ./../front-end/.env
    environment:
      NODE_ENV: production
      API_HOST: "http://back-end:${BACKEND_PORT:-5000}/api"
    networks:
      - frontend

networks:
  frontend:
