---
version: "3.5"
services:

  back-end:
    restart: "on-failure"
    build:
      context: ./../back-end
      dockerfile: ./../config/Dockerfile-backend
    ports:
      - "5000:5000"

  front-end:
    restart: "on-failure"
    build:
      context: ./../front-end
      dockerfile: ./../config/Dockerfile-frontend
    ports:
      - "80:3000"
